version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t zapthedingbat/repository-report:$CIRCLE_SHA1 .
      - run: docker tag zapthedingbat/repository-report:$CIRCLE_SHA1 zapthedingbat/repository-report:latest
      - run: docker push zapthedingbat/repository-report
  generate-report:
    machine: true
    steps:
      - run: mkdir $(pwd)/.keys
      - run: echo $GITHUB_PRIVATE_KEY | base64 --decode > $(pwd)/.keys/github-private-key.pem
      - run: env > $(pwd)/.env
      - run: mkdir /tmp/.reports
      - run: chmod -R 777 /tmp/.reports
      - run: >
          docker run
          --rm
          --env-file=.env
          -v $(pwd)/.keys:/home/app/.keys
          -v /tmp/.reports:/home/app/.reports
          zapthedingbat/repository-report
      - store_artifacts:
          path: /tmp/.reports
workflows:
  version: 2
  build:
    jobs:
      - build
      - generate-report:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate-report
