version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: docker build
          command: docker build -t zapthedingbat/repository-report:$CIRCLE_SHA1 .
  deploy:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Publish to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag zapthedingbat/repository-report:$CIRCLE_SHA1 zapthedingbat/repository-report:latest
            docker push zapthedingbat/repository-report
  generate-report:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Write environment config to file
          command: env > $(pwd)/.env
      - run:
          name: Write github private key
          command: |
            mkdir $(pwd)/.keys
            echo $GITHUB_PRIVATE_KEY | base64 --decode > $(pwd)/.keys/github-private-key.pem
            docker create -v /var/src/app/.keys --name keys alpine /bin/true
            docker cp $(pwd)/.keys/github-private-key.pem keys:/var/src/app/.keys
      - run:
          name: Generate report
          command: >
            docker run
            --name app
            --env-file=.env
            --volumes-from keys
            zapthedingbat/repository-report
      - run:
          name: Copy artifacts
          command: |
            docker cp app:/var/src/app/.reports /tmp/.reports
      - store_artifacts:
          path: /tmp/.reports
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - generate-report:
          requires:
            - deploy
  nightly:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate-report
