version: 2
jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: docker build
          command: docker build -t zapthedingbat/repository-report:$CIRCLE_SHA1 .
  deploy:
    machine: true
    steps:
      - run:
          name: Publish to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag zapthedingbat/repository-report:$CIRCLE_SHA1 zapthedingbat/repository-report:latest
            docker push zapthedingbat/repository-report
  generate-report:
    machine: true
    steps:
      - run:
          name: Configure environment
          command: |
            mkdir $(pwd)/.keys
            echo $GITHUB_PRIVATE_KEY | base64 --decode > $(pwd)/.keys/github-private-key.pem
            env > $(pwd)/.env
            mkdir /tmp/.reports
            chmod -R 777 /tmp/.reports
      - run:
          name: Generate report
          command: >
            docker run
            --rm
            --env-file=.env
            -v $(pwd)/.keys:/home/app/.keys
            -v /tmp/.reports:/home/app/.reports
            zapthedingbat/repository-report
      - store_artifacts:
          path: /tmp/.reports
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - generate-report:
          requires:
            - deploy
  nightly:
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate-report
